### ISSUE TITLE
Cake-Resque on Windows

### ISSUE THREAD

**Issue by hgsolenzal** [kamisama/Cake-Resque#101]
Hello,

I haven't been able to successfully install the plugin on Windows. I'm trying to do so using composer, but (since I'm on Windows) I'm getting the requires ext-pcntl error coming from the php-resque requirements. Is there a known workaround to solve this problem? Some solution that doesn't require the pcntl extension?

Thanks!

**Comment by wa0x6e** [comment]
Hi,

AFAIK, the extension is not available on windows, at least with php 5, I did not try with php7.
There is no workaround, that extension is used to manage process (and thus workers).

You can try your luck with a virtual machine or docker
