### ISSUE TITLE
Roadmap for Cake3

### ISSUE THREAD

**Issue by amiri27** [kamisama/Cake-Resque#84]
Hi Kamisama,

Thank you for this very well working plugin.. I wanna just know if there's any roadmap for Cake3 compatibility and how can we help on that?

Regards,

**Comment by kallealberg** [comment]
Looks like theres a guy working on a Cake3 fork:
https://github.com/RTLer/Cake-Resque

**Comment by kamisama** [comment]
Let's wait for his PR :)

**Comment by amiri27** [comment]
Hi Kamisama,

This guy is from our team.. We already finished everything and ready to send a PR.. Also if it's possible we need to a PR to php-resque-ex in order to add deque method which is already added on php-rasque..

Regards,

**Comment by kamisama** [comment]
Awesome ;)

**Comment by manierim** [comment]
There are a couple of PR here and for php-resque-ex that make the job works in CakePHP 3. Hope them helps...

**Comment by oanhnn** [comment]
Ping @wa0x6e , 
Now, Is CakeResque ready for CakePHP v3.x ?

**Comment by kallealberg** [comment]
Master branch should be 3.x ready, haven't tested it tho.
