### ISSUE TITLE
 Unable to get primary namespace for package kamisama/cake-resque.

### ISSUE THREAD

**Issue by manierim** [kamisama/Cake-Resque#91]
Trying to add kamisama/cake-resque to my composer.json and then running composer install produces:

`Script Cake\Composer\Installer\PluginInstaller::postAutoloadDump handling the post-autoload-dump event terminated with an exception`

`[RuntimeException]
  Unable to get primary namespace for package kamisama/cake-resque.
  Ensure you have added proper 'autoload' section to your plugin's config as stated in README on https://github.com/cakephp/plugin-installer`

Autoload then fails in cake (`Error: Class 'CakeResque' not found`)

**Comment by wa0x6e** [comment]
What version of CakePHP are you using ?

**Comment by manierim** [comment]
3.0.10

**Comment by wa0x6e** [comment]
CakeResque is not compatible CakePHP 3 yet

**Comment by manierim** [comment]
Ah ok, seeing the master branch being on the work for cakephp 3 I thought it was, sorry

**Comment by manierim** [comment]
my mistake, I was not pointing composer to dev-master. I need to figure out a few things but seems the port is mainly working
